var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,b){a instanceof String&&(a=String(a));for(var f=a.length,h=0;h<f;h++){var c=a[h];if(e.call(b,c,h,a))return{i:h,v:c}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,b,f){if(e){b=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var h=a[f];h in b||(b[h]={});b=b[h]}a=a[a.length-1];f=b[a];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");
(function(){var a=[],e=0;window.generate_the_wcmp=function(b){function f(g,l){if(g+1<e||l){var d=g+1;!l||d!=e&&0!=c('[playernumber="'+d+'"]').closest("[data-loop]").length&&c('[playernumber="'+d+'"]').closest("[data-loop]")[0]==c('[playernumber="'+g+'"]').closest("[data-loop]")[0]||(d=c('[playernumber="'+g+'"]').closest("[data-loop]").find("[playernumber]:first").attr("playernumber"));a[d]instanceof c&&a[d].is("a")?a[d].is(":visible")?a[d].click():f(g+1,l):c(a[d].container).is(":visible")?a[d].play():
f(g+1,l)}}function h(g){var a=g.data("product"),d=c("img.product-"+a);d.length&&1==c('[data-product="'+a+'"]').length&&(a=d.offset(),g=g.closest("div.wcmp-player"),g.css({position:"absolute","z-index":999999}).offset({left:a.left+(d.width()-g.width())/2,top:a.top+(d.height()-g.height())/2}))}if(!("boolean"!==typeof b&&"undefined"!=typeof wcmp_global_settings&&1*wcmp_global_settings.onload)&&"undefined"===typeof generated_the_wcmp){generated_the_wcmp=!0;var c=jQuery;c(".wcmp-player-container").on("click",
"*",function(a){a.preventDefault();a.stopPropagation();return!1});c.expr[":"].regex=function(a,b,d){b=d[3].split(",");var m=/^(data|css):/;d=b[0].match(m)?b[0].split(":")[0]:"attr";m=b.shift().replace(m,"");return(new RegExp(b.join("").replace(/^\s+|\s+$/g,""),"ig")).test(c(a)[d](m))};var r="undefined"!=typeof wcmp_global_settings?wcmp_global_settings.play_all:!0,k="undefined"!=typeof wcmp_global_settings?!(1*wcmp_global_settings.play_simultaneously):!0,p="undefined"!=typeof wcmp_global_settings?
1*wcmp_global_settings.fade_out:!0,q="undefined"!=typeof wcmp_global_settings&&"ios_controls"in wcmp_global_settings&&1*wcmp_global_settings.ios_controls?!0:!1;b=c("audio.wcmp-player:not(.track):not([playernumber])");var t=c("audio.wcmp-player.track:not([playernumber])"),n={pauseOtherPlayers:k,iPadUseNativeControls:q,iPhoneUseNativeControls:q,success:function(a,b){c(b).attr("volume")&&a.setVolume(parseFloat(c(b).attr("volume")));var d=function(a){a=c(a.target||a.detail.target);var m=a.data("duration");
"undefined"!=typeof m&&a.closest(".wcmp-player-container").find(".mejs-duration").html(m)};a.addEventListener("timeupdate",function(a){d(a);a=a.target||a.detail.target;isNaN(a.currentTime)||isNaN(a.duration)||(p&&4>a.duration-a.currentTime?a.setVolume(a.volume-a.volume/3):("undefined"==typeof a.bkVolume&&(a.bkVolume=a.volume),a.setVolume(a.bkVolume)))});a.addEventListener("volumechange",function(a){a=a.target||a.detail.target;isNaN(a.currentTime)||isNaN(a.duration)||!(4<a.duration-a.currentTime)&&
p||!a.currentTime||(a.bkVolume=a.volume)});a.addEventListener("ended",function(a){var b=a.target||a.detail.target;a=c(b).closest('[data-loop="1"]');if(1*r||a.length)b=1*c(b).attr("playernumber"),f(b,a.length)});a.addEventListener("loadedmetadata",function(a){d(a)})}};k=".product-type-grouped :regex(name,quantity\\[\\d+\\])";b.each(function(){var b=c(this);b.find("source").attr("src");b.attr("playernumber",e);n.audioVolume="vertical";try{a[e]=new MediaElementPlayer(b[0],n)}catch(l){"console"in window&&
console.log(l)}e++});t.each(function(){var b=c(this);b.find("source").attr("src");b.attr("playernumber",e);n.features=["playpause"];try{a[e]=new MediaElementPlayer(b[0],n)}catch(l){"console"in window&&console.log(l)}e++;h(b);c(window).resize(function(){h(b)})});c(k).length||(k=".product-type-grouped [data-product_id]");c(k).length||(k=".woocommerce-grouped-product-list [data-product_id]");c(k).length||(k='.woocommerce-grouped-product-list [id*="product-"]');c(k).each(function(){try{var a=c(this),
b=(a.data("product_id")||a.attr("name")||a.attr("id")).replace(/[^\d]/g,""),d=c(".wcmp-player-list.merge_in_grouped_products .product-"+b+":first .wcmp-player-title"),e=c("<table></table>");d.length&&!d.closest(".wcmp-first-in-product").length&&(d.closest("tr").addClass("wcmp-first-in-product"),0==d.closest("form").length&&d.closest(".wcmp-player-list").prependTo(a.closest("form")),e.append(a.closest("tr").prepend("<td>"+d.html()+"</td>")),d.html("").append(e))}catch(u){}})}};window.wcmp_force_init=
function(){delete window.generated_the_wcmp;generate_the_wcmp(!0)};jQuery(generate_the_wcmp);jQuery(window).on("load",function(){generate_the_wcmp(!0);var a=jQuery,e=window.navigator.userAgent;a("[data-lazyloading]").each(function(){var b=a(this);b.attr("preload",b.data("lazyloading"))});if(e.match(/iPad/i)||e.match(/iPhone/i))if("undefined"!=typeof wcmp_global_settings?wcmp_global_settings.play_all:1)a(".wcmp-player .mejs-play button").one("click",function(){if("undefined"==typeof wcmp_preprocessed_players){wcmp_preprocessed_players=
!0;var b=a(this);a(".wcmp-player audio").each(function(){this.play();this.pause()});setTimeout(function(){b.click()},500)}})}).on("popstate",function(){jQuery("audio[data-product]:not([playernumber])").length&&wcmp_force_init()});jQuery(document).on("scroll wpfAjaxSuccess woof_ajax_done yith-wcan-ajax-filtered wpf_ajax_success berocket_ajax_products_loaded",wcmp_force_init)})();
